# Generated by Django 3.2.7 on 2021-11-08 07:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_ar', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('image_author', models.ImageField(default='assets/img/Business-elite-logo-none-bg.png', upload_to='post/', verbose_name='image_author')),
                ('description_author', models.TextField(blank=True, max_length=1500, null=True, verbose_name='description_author')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('post_views', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='post/', verbose_name='image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('description_one', models.TextField(max_length=20000, verbose_name='description')),
                ('description_two', models.TextField(max_length=20000, verbose_name='description')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='url')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='blog.category', verbose_name='category')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
            ],
        ),
    ]
