# Generated by Django 3.2.7 on 2021-10-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_author',
            field=models.ImageField(default=2, upload_to='post/', verbose_name='image_author'),
            preserve_default=False,
        ),
    ]
