# Generated by Django 3.2.7 on 2021-11-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_author',
            field=models.ImageField(default='Business-elite-logo-none-bg.png', upload_to='post/', verbose_name='image_author'),
        ),
    ]
