# Generated by Django 3.2.7 on 2021-10-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description_author',
            field=models.TextField(default=2, max_length=15000, verbose_name='description_author'),
            preserve_default=False,
        ),
    ]
