# Generated by Django 3.2.7 on 2021-11-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211108_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description_author_ar',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description_author_en',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description_one_ar',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description_one_en',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description_two_ar',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description_two_en',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
