# Generated by Django 3.2.7 on 2021-10-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_description_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description_author',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='description_author'),
        ),
    ]
