# Generated by Django 3.2.7 on 2021-11-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_author',
            field=models.ImageField(upload_to='post/'),
        ),
    ]
