# Generated by Django 3.2.7 on 2021-11-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_image_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description_author',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_author_ar',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_author_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_one',
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_one_ar',
            field=models.TextField(max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_one_en',
            field=models.TextField(max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_two',
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_two_ar',
            field=models.TextField(max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_two_en',
            field=models.TextField(max_length=50000, null=True),
        ),
    ]
