# Generated by Django 3.2.7 on 2021-11-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211110_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tags_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_one',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_one_ar',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_one_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_two',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_two_ar',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_two_en',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
