# Generated by Django 3.2.7 on 2021-11-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20211110_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_author',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
    ]
