# Generated by Django 3.2.7 on 2021-11-06 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_ar', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_section', models.CharField(blank=True, max_length=100, null=True)),
                ('title_section_en', models.CharField(blank=True, max_length=100, null=True)),
                ('title_section_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('description_section', models.TextField(blank=True, max_length=10000, null=True)),
                ('description_section_en', models.TextField(blank=True, max_length=10000, null=True)),
                ('description_section_ar', models.TextField(blank=True, max_length=10000, null=True)),
                ('image_section', models.ImageField(blank=True, null=True, upload_to='detail_page/')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ar', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='properties.category')),
            ],
        ),
        migrations.CreateModel(
            name='DetailSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True)),
                ('title_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('description_en', models.TextField(blank=True, max_length=10000, null=True)),
                ('description_ar', models.TextField(blank=True, max_length=10000, null=True)),
                ('message', models.TextField(blank=True, max_length=10000, null=True)),
                ('message_en', models.TextField(blank=True, max_length=10000, null=True)),
                ('message_ar', models.TextField(blank=True, max_length=10000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='detail_page/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_sub_category', to='properties.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CardsProgramUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_program', models.CharField(blank=True, max_length=30, null=True)),
                ('title_program', models.CharField(blank=True, max_length=100, null=True)),
                ('title_program_en', models.CharField(blank=True, max_length=100, null=True)),
                ('title_program_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('description_program', models.TextField(blank=True, max_length=10000, null=True)),
                ('description_program_en', models.TextField(blank=True, max_length=10000, null=True)),
                ('description_program_ar', models.TextField(blank=True, max_length=10000, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_units_category', to='properties.detailsubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CardsFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_card', models.CharField(blank=True, max_length=30, null=True)),
                ('title_card', models.CharField(blank=True, max_length=60, null=True)),
                ('title_card_en', models.CharField(blank=True, max_length=60, null=True)),
                ('title_card_ar', models.CharField(blank=True, max_length=60, null=True)),
                ('description_card', models.TextField(blank=True, max_length=10000, null=True)),
                ('description_card_en', models.TextField(blank=True, max_length=10000, null=True)),
                ('description_card_ar', models.TextField(blank=True, max_length=10000, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_category', to='properties.detailsubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CardEliteHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True)),
                ('title_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('description_en', models.TextField(blank=True, max_length=10000, null=True)),
                ('description_ar', models.TextField(blank=True, max_length=10000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_page/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_elite_home', to='properties.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CardDoxHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True)),
                ('title_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('description_en', models.TextField(blank=True, max_length=10000, null=True)),
                ('description_ar', models.TextField(blank=True, max_length=10000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_page/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_dox_home', to='properties.subcategory')),
            ],
        ),
    ]
