# Generated by Django 3.2.7 on 2021-11-07 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsection',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detail_section', to='properties.detailsubcategory'),
            preserve_default=False,
        ),
    ]
